# uncomment the line below to test local
# local_backend: true
backend:
  # uncomment the line below to test local, and not to save the change
  # name: test-repo
  name: git-gateway
  branch: netlify-cms
publish_mode: editorial_workflow
media_folder: "mock/uploads"
collections:
  - name: "thematic"
    label: "thematic"
    folder: "mock/thematic"
    media_folder: "mock/thematic"
    create: true
    extension: 'mdx'
    format: 'frontmatter'
    title: fields.id
    identifier_field: fields.id
    slug: "{{fields.id}}.thematic"
    summary: "{{fields.name}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Thematic name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "About"
        name: "about"
        widget: 'object'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'string'}
      - label: "Image"
        name: "media"
        widget: 'object'
        fields:
          - {label: 'File', name: 'src', widget: 'image'}
          - {label: 'Alt text', name: 'alt', widget: 'string'}
          - label: 'Author' 
            name: 'author'
            widget: 'object'
            fields:
              - {label: 'Name', name: 'name', widget: 'string'}
              - {label: 'URL', name: 'url', widget: 'string'}
  - name: "dataset"
    label: "Dataset"
    folder: "mock/datasets"
    media_folder: "mock/datasets"
    editor:
      preview: false
    create: true
    extension: 'mdx'
    format: 'frontmatter'
    title: fields.id
    identifier_field: fields.id
    slug: "{{fields.id}}.data"
    preview_path: "{{fields.thematics[0]}}/datasets/{{fields.id}}/explore"
    summary: "{{fields.name}}"
    fields:
      - label: "Featured on"
        name: "featuredOn"
        widget: "select"
        multiple: true
        options: ["agriculture", "air-quality", "covid-19"]
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Thematics"
        name: "thematics"
        widget: "select"
        multiple: true
        options: ["agriculture", "air-quality", "covid-19"]
      - label: "Image"
        name: "media"
        widget: 'object'
        fields:
          - {label: 'File', name: 'src', widget: 'image'}
          - {label: 'Alt text', name: 'alt', widget: 'string'}
          - label: 'Author' 
            name: 'author'
            widget: 'object'
            fields:
              - {label: 'Name', name: 'name', widget: 'string'}
              - {label: 'URL', name: 'url', widget: 'string'}
      - label: "Layers"
        name: layers
        widget: list
        fields: 
          - {label: "ID", name: "id", widget: "string"}
          - label: STAC ID
            name: stacCol
            widget: select-async
            # widget options:
            url: https://staging-stac.delta-backend.com/collections
            data_path:  collections
            value_field: id
            display_field: id
          - label: "Layer Name"
            name: 'name'
            widget: "string"
          - label: "Description"
            name: 'description'
            widget: "string"
          - label: "type"
            name: type
            widget: "string"
            default: "raster"
          - label: "Zoom Extent"
            name: zoomExtent
            widget: list
          - label: 'Source parameter'
            name: sourceParams
            widget: object
            fields:
              - label: rescale
                name: rescale
                widget: list
                required: false
              - label: bidx
                name: bidx
                widget: string
                required: false
              - label: colormap name
                name: colormap_name
                widget: string
                required: false
          - label: "Legend"
            name: "legend"
            widget: "object"
            fields:
            - {label: "Type", name: "type", widget: "select", options: ['categorical','gradient'] }
            - {label: "Min value label", name: "min", widget: "string" }
            - {label: "Max value label", name: "max", widget: "string" }
            - label: "Stops for Gradient"
              name: "stops"
              widget: list
          - label: Projection
            name: projection
            widget: object
            required: false
            fields:
              - {label: "ID", name: "id", widget: "select", options: ['albers', 'equalEarth', 'equirectangular', 'lambertConformalConic', 'mercator', 'naturalEarth', 'winkelTripel', 'globe', 'polarNorth', 'polarSouth'] }
              - {label: "Center (float, float)", name: "center", widget: "list" }
              - {label: "Parallels (float, float) ", name: "parallels", widget: "list" }

        # - label: "Stops for Category"
        #   name: "stops"
        #   widget: "list"
        #   fields:
        #     - {label: "color", name: "", widget: "text" }
        #     - {label: "label", name: "label", widget: "text" }

