name: PR Title Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix", "docs", "test", "ci", "refactor", "chore", "revert"]'
          add_label: 'false'